name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setting up Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Make data directory
        run: mkdir data
      - name: Run Tests
        run: go test